/* Kreiranje tablice VEZNA1 s primarnim i stranim kljucevima */
CREATE TABLE VEZNA1 (
    TABID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
        (START WITH 1 INCREMENT BY 1 NO MAXVALUE ORDER), /* TABID - ID veze */
    TABIDAUT INTEGER NOT NULL, /* TABIDAUT - ID autora (strani kljuc) */
    TABIDKNJ INTEGER NOT NULL, /* TABIDKNJ - ID knjige (strani kljuc) */
    
    /* Definiranje primarnog kljuca s imenom */
    CONSTRAINT PK_VEZNA1 PRIMARY KEY (TABID), 

    /* Definiranje stranog kljuca za autore */
    CONSTRAINT FK_VEZNA1_AUT FOREIGN KEY (TABIDAUT) 
        REFERENCES AUTORI(TABID) 
        ON DELETE NO ACTION, 

    /* Definiranje stranog kljuca za knjige */
    CONSTRAINT FK_VEZNA1_KNJ FOREIGN KEY (TABIDKNJ) 
        REFERENCES KNJIGE(TABID) 
        ON DELETE NO ACTION
);

/* Kreiranje jedinstvenog indeksa za primarni kljuc */
CREATE UNIQUE INDEX IDX_UNIQUE_VEZNA1_ID ON VEZNA1 (TABID);

/* Kreiranje view-a za tablicu VEZNA1 */
CREATE VIEW VIEW_VEZNA1 AS
    SELECT 
        TABID AS ID, /* ID veze */
        TABIDAUT AS IDAUT, /* ID autora */
        TABIDKNJ AS IDKNJ /* ID knjige */
    FROM VEZNA1;

/* Dodavanje komentara na stupce */
COMMENT ON COLUMN VEZNA1.TABID IS 'TABID - ID veze';
COMMENT ON COLUMN VEZNA1.TABIDAUT IS 'TABIDAUT - ID autora';
COMMENT ON COLUMN VEZNA1.TABIDKNJ IS 'TABIDKNJ - ID knjige';
