/* Kreiranje tablice CLANOVI s primarnim kljucem */
CREATE TABLE CLANOVI (
    TABID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
        (START WITH 1 INCREMENT BY 1 NO MAXVALUE ORDER), /* TABID - ID clana */
    TABPREZ VARCHAR(60) NOT NULL, /* TABPREZ - Prezime clana */
    TABIME VARCHAR(60), /* TABIME - Ime clana */
    TABDATOD DATE, /* TABDATOD - Datum uclanjenja */
    TABSTATUS INTEGER, /* TABSTATUS - Status clana */
    
    /* Definiranje primarnog kljuca s imenom */
    CONSTRAINT PK_CLANOVI PRIMARY KEY (TABID)
);

/* Kreiranje jedinstvenog indeksa za primarni kljuc */
CREATE UNIQUE INDEX IDX_UNIQUE_CLANOVI_ID ON CLANOVI (TABID);

/* Kreiranje view-a za tablicu CLANOVI */
CREATE VIEW VIEW_CLANOVI AS
    SELECT 
        TABID AS ID, /* ID clana */
        TABPREZ AS PREZ, /* Prezime clana */
        TABIME AS IME, /* Ime clana */
        TABDATOD AS DATOD, /* Datum uclanjenja */
        TABSTATUS AS STATUS /* Status clana */
    FROM CLANOVI;

/* Dodavanje komentara na stupce */
COMMENT ON COLUMN CLANOVI.TABID IS 'TABID - ID clana';
COMMENT ON COLUMN CLANOVI.TABPREZ IS 'TABPREZ - Prezime clana';
COMMENT ON COLUMN CLANOVI.TABIME IS 'TABIME - Ime clana';
COMMENT ON COLUMN CLANOVI.TABDATOD IS 'TABDATOD - Datum uclanjenja';
COMMENT ON COLUMN CLANOVI.TABSTATUS IS 'TABSTATUS - Status clana';
