/* Kreiranje tablice ZAKAS s primarnim i stranim kljucevima */
CREATE TABLE ZAKAS (
    TABID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
        (START WITH 1 INCREMENT BY 1 NO MAXVALUE ORDER), /* TABID - ID zakasnine */
    TABIDCLAN INTEGER NOT NULL, /* TABIDCLAN - ID clana (strani kljuc) */
    TABIDPOS INTEGER NOT NULL, /* TABIDPOS - ID posudbe (strani kljuc) */
    TABZAKDAT DATE, /* TABZAKDAT - Datum zakasnine */
    TABIZNOS INTEGER, /* TABIZNOS - Iznos zakasnine */
    
    /* Definiranje primarnog kljuca s imenom */
    CONSTRAINT PK_ZAKAS PRIMARY KEY (TABID), 

    /* Definiranje stranog kljuca za clanove */
    CONSTRAINT FK_ZAKAS_CLAN FOREIGN KEY (TABIDCLAN) 
        REFERENCES CLANOVI(TABID) 
        ON DELETE NO ACTION, 

    /* Definiranje stranog kljuca za posudbe */
    CONSTRAINT FK_ZAKAS_POS FOREIGN KEY (TABIDPOS) 
        REFERENCES POSUDBA(TABID) 
        ON DELETE NO ACTION
);

/* Kreiranje jedinstvenog indeksa za primarni kljuc */
CREATE UNIQUE INDEX IDX_UNIQUE_ZAKAS_ID ON ZAKAS (TABID);

/* Kreiranje view-a za tablicu ZAKAS */
CREATE VIEW VIEW_ZAKAS AS
    SELECT 
        TABID AS ID, /* ID zakasnine */
        TABIDCLAN AS IDCLAN, /* ID clana */
        TABIDPOS AS IDPOS, /* ID posudbe */
        TABZAKDAT AS ZAKDAT, /* Datum zakasnine */
        TABIZNOS AS IZNOS /* Iznos zakasnine */
    FROM ZAKAS;

/* Dodavanje komentara na stupce */
COMMENT ON COLUMN ZAKAS.TABID IS 'TABID - ID zakasnine';
COMMENT ON COLUMN ZAKAS.TABIDCLAN IS 'TABIDCLAN - ID clana';
COMMENT ON COLUMN ZAKAS.TABIDPOS IS 'TABIDPOS - ID posudbe';
COMMENT ON COLUMN ZAKAS.TABZAKDAT IS 'TABZAKDAT - Datum zakasnine';
COMMENT ON COLUMN ZAKAS.TABIZNOS IS 'TABIZNOS - Iznos zakasnine';
