/* Kreiranje tablice POSUDBA s primarnim i stranim kljucevima */
CREATE TABLE POSUDBA (
    TABID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
        (START WITH 1 INCREMENT BY 1 NO MAXVALUE ORDER), /* TABID - ID posudbe */
    TABIDKNJ INTEGER NOT NULL, /* TABIDKNJ - ID knjige (strani kljuc) */
    TABIDCLAN INTEGER NOT NULL, /* TABIDCLAN - ID clana (strani kljuc) */
    TABDATPOS DATE, /* TABDATPOS - Datum posudbe */
    
    /* Definiranje primarnog kljuca s imenom */
    CONSTRAINT PK_POSUDBA PRIMARY KEY (TABID), 

    /* Definiranje stranog kljuca za knjige */
    CONSTRAINT FK_POSUDBA_KNJIGA FOREIGN KEY (TABIDKNJ) 
        REFERENCES KNJIGE(TABID) 
        ON DELETE NO ACTION, 

    /* Definiranje stranog kljuca za clanove */
    CONSTRAINT FK_POSUDBA_CLAN FOREIGN KEY (TABIDCLAN) 
        REFERENCES CLANOVI(TABID) 
        ON DELETE NO ACTION
);

/* Kreiranje jedinstvenog indeksa za primarni kljuc */
CREATE UNIQUE INDEX IDX_UNIQUE_POSUDBA_ID ON POSUDBA (TABID);

/* Kreiranje view-a za tablicu POSUDBA */
CREATE VIEW VIEW_POSUDBA AS
    SELECT 
        TABID AS ID, /* ID posudbe */
        TABIDKNJ AS IDKNJ, /* ID knjige */
        TABIDCLAN AS IDCLAN, /* ID clana */
        TABDATPOS AS DATPOS /* Datum posudbe */
    FROM POSUDBA;

/* Dodavanje komentara na stupce */
COMMENT ON COLUMN POSUDBA.TABID IS 'TABID - ID posudbe';
COMMENT ON COLUMN POSUDBA.TABIDKNJ IS 'TABIDKNJ - ID knjige';
COMMENT ON COLUMN POSUDBA.TABIDCLAN IS 'TABIDCLAN - ID clana';
COMMENT ON COLUMN POSUDBA.TABDATPOS IS 'TABDATPOS - Datum posudbe';
