/* Kreiranje tablice REZERV s primarnim i stranim kljucevima */
CREATE TABLE REZERV (
    TABID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
        (START WITH 1 INCREMENT BY 1 NO MAXVALUE ORDER), /* TABID - ID rezervacije */
    TABIDKNJ INTEGER NOT NULL, /* TABIDKNJ - ID knjige (strani kljuc) */
    TABIDCLAN INTEGER NOT NULL, /* TABIDCLAN - ID clana (strani kljuc) */
    TABDATREZ DATE, /* TABDATREZ - Datum rezervacije */
    TABREZSTAT INTEGER, /* TABREZSTAT - Status rezervacije */
    
    /* Definiranje primarnog kljuca s imenom */
    CONSTRAINT PK_REZERV PRIMARY KEY (TABID), 

    /* Definiranje stranog kljuca za knjige */
    CONSTRAINT FK_REZERV_KNJ FOREIGN KEY (TABIDKNJ) 
        REFERENCES KNJIGE(TABID) 
        ON DELETE NO ACTION, 

    /* Definiranje stranog kljuca za clanove */
    CONSTRAINT FK_REZERV_CLAN FOREIGN KEY (TABIDCLAN) 
        REFERENCES CLANOVI(TABID) 
        ON DELETE NO ACTION
);

/* Kreiranje jedinstvenog indeksa za primarni kljuc */
CREATE UNIQUE INDEX IDX_UNIQUE_REZERV_ID ON REZERV (TABID);

/* Kreiranje view-a za tablicu REZERV */
CREATE VIEW VIEW_REZERV AS
    SELECT 
        TABID AS ID, /* ID rezervacije */
        TABIDKNJ AS IDKNJ, /* ID knjige */
        TABIDCLAN AS IDCLAN, /* ID clana */
        TABDATREZ AS DATREZ, /* Datum rezervacije */
        TABREZSTAT AS REZSTAT /* Status rezervacije */
    FROM REZERV;

/* Dodavanje komentara na stupce */
COMMENT ON COLUMN REZERV.TABID IS 'TABID - ID rezervacije';
COMMENT ON COLUMN REZERV.TABIDKNJ IS 'TABIDKNJ - ID knjige';
COMMENT ON COLUMN REZERV.TABIDCLAN IS 'TABIDCLAN - ID clana';
COMMENT ON COLUMN REZERV.TABDATREZ IS 'TABDATREZ - Datum rezervacije';
COMMENT ON COLUMN REZERV.TABREZSTAT IS 'TABREZSTAT - Status rezervacije';
