/* Kreiranje tablice DOBAVLJ s primarnim kljucem */
CREATE TABLE DOBAVLJ (
    TABID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
        (START WITH 1 INCREMENT BY 1 NO MAXVALUE ORDER), /* TABID - ID dobavljaca */
    TABNAZIV VARCHAR(60) NOT NULL, /* TABNAZIV - Naziv dobavljaca */
    TABKONTBR INTEGER, /* TABKONTBR - Kontakt broj */
    
    /* Definiranje primarnog kljuca s imenom */
    CONSTRAINT PK_DOBAVLJ PRIMARY KEY (TABID)
);

/* Kreiranje jedinstvenog indeksa za primarni kljuc */
CREATE UNIQUE INDEX IDX_UNIQUE_DOBAVLJ_ID ON DOBAVLJ (TABID);

/* Kreiranje view-a za tablicu DOBAVLJ */
CREATE VIEW VIEW_DOBAVLJ AS
    SELECT 
        TABID AS ID, /* ID dobavljaca */
        TABNAZIV AS NAZIV, /* Naziv dobavljaca */
        TABKONTBR AS KONTBR /* Kontakt broj */
    FROM DOBAVLJ;

/* Dodavanje komentara na stupce */
COMMENT ON COLUMN DOBAVLJ.TABID IS 'TABID - ID dobavljaca';
COMMENT ON COLUMN DOBAVLJ.TABNAZIV IS 'TABNAZIV - Naziv dobavljaca';
COMMENT ON COLUMN DOBAVLJ.TABKONTBR IS 'TABKONTBR - Kontakt broj';
