/* Kreiranje tablice KNJIGE s primarnim kljuèem */
CREATE TABLE KNJIGE (
    TABID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
        (START WITH 1 INCREMENT BY 1 NO MAXVALUE ORDER), /* TABID - ID knjige */
    TABNAZIV VARCHAR(60) NOT NULL, /* TABNAZIV - Naziv knjige */
    TABAUTOR VARCHAR(60), /* TABAUTOR - Naziv autora knjige */
    TABKATGRJ VARCHAR(20), /* TABKATGRJ - Kategorija knjige */
    TABGODIZD INTEGER, /* TABGODIZD - Godina izdanja */
    TABBRKNJ INTEGER, /* TABBRKNJ - Broj knjige */
    
    /* Definiranje primarnog kljuèa s imenom */
    CONSTRAINT PK_KNJIGE PRIMARY KEY (TABID)
);

/* Kreiranje jedinstvenog indeksa za primarni kljuè */
CREATE UNIQUE INDEX IDX_UNIQUE_KNJIGE_ID ON KNJIGE (TABID);

/* Kreiranje view-a za tablicu KNJIGE */
CREATE VIEW VIEW_KNJIGE AS
    SELECT 
        TABID AS ID, /* ID knjige */
        TABNAZIV AS NAZIV, /* Naziv knjige */
        TABAUTOR AS AUTOR, /* Naziv autora */
        TABKATGRJ AS KATGRJ, /* Kategorija knjige */
        TABGODIZD AS GODIZD, /* Godina izdanja */
        TABBRKNJ AS BRKNJ /* Broj knjige */
    FROM KNJIGE;

/* Dodavanje komentara na stupce */
COMMENT ON COLUMN KNJIGE.TABID IS 'TABID - ID knjige';
COMMENT ON COLUMN KNJIGE.TABNAZIV IS 'TABNAZIV - Naziv knjige';
COMMENT ON COLUMN KNJIGE.TABAUTOR IS 'TABAUTOR - Naziv autora knjige';
COMMENT ON COLUMN KNJIGE.TABKATGRJ IS 'TABKATGRJ - Kategorija knjige';
COMMENT ON COLUMN KNJIGE.TABGODIZD IS 'TABGODIZD - Godina izdanja';
COMMENT ON COLUMN KNJIGE.TABBRKNJ IS 'TABBRKNJ - Broj knjige';
